version: '3'
services:
  borse:
    build:
      context: .
      dockerfile: src/main/java/org/borse/Dockerfile
    container_name: 'borse'
    entrypoint: ["java", "-jar", "app.jar","bank1","1234","bank2","1235"]
  bank1:
    build:
      context: .
      dockerfile: src/main/java/org/bank/Dockerfile
    container_name: 'bank1'
    entrypoint: ["java", "-jar", "app.jar", "bank1","1234"]
  bank2:
    build:
      context: .
      dockerfile: src/main/java/org/bank/Dockerfile
    container_name: 'bank2'
    entrypoint: ["java", "-jar", "app.jar", "bank2","1235"]