version: '3'
services:
  borse1:
    build:
      context: .
      dockerfile: src/main/java/org/borse/Dockerfile
    container_name: 'borse1'
    entrypoint: ["java", "-jar", "app.jar","bank1","1234","bank2","1235","bank3","1236","borse1"]
  borse2:
    build:
      context: .
      dockerfile: src/main/java/org/borse/Dockerfile
    container_name: 'borse2'
    entrypoint: [ "java", "-jar", "app.jar","bank1","1234","bank2","1235","bank3","1236","borse2" ]

  bank1:
    build:
      context: .
      dockerfile: src/main/java/org/bank/Dockerfile
    container_name: 'bank1'
    expose:
      - "8080"
    ports:
      - "8080:8080"
    entrypoint: ["java", "-jar", "app.jar", "bank1","1234","8080"]
  bank2:
    build:
      context: .
      dockerfile: src/main/java/org/bank/Dockerfile
    container_name: 'bank2'
    expose:
      - "8081"
    ports:
      - "8081:8081"
    entrypoint: [ "java", "-jar", "app.jar","bank2","1235","8081"]
  bank3:
    build:
      context: .
      dockerfile: src/main/java/org/bank/Dockerfile
    container_name: 'bank3'
    expose:
      - "8082"
    ports:
      - "8082:8082"
    entrypoint: [ "java", "-jar", "app.jar","bank3","1236","8082"]