version: '3'
services:
  borse1:
    build:
      context: .
      dockerfile: src/main/java/borse/Dockerfile
    container_name: 'borse1'
    entrypoint: ["java", "-jar", "app.jar","bank1","1234","bank2","1235","bank3","1236","borse1"]
  borse2:
    build:
      context: .
      dockerfile: src/main/java/borse/Dockerfile
    container_name: 'borse2'
    entrypoint: [ "java", "-jar", "app.jar","bank1","1234","bank2","1235","bank3","1236","borse2" ]
  borse3:
    build:
      context: .
      dockerfile: src/main/java/borse/Dockerfile
    container_name: 'borse3'
    entrypoint: [ "java", "-jar", "app.jar","bank1","1234","bank2","1235","bank3","1236","bank4","1237","bank5","1238","borse3" ]
  borse4:
    build:
      context: .
      dockerfile: src/main/java/borse/Dockerfile
    container_name: 'borse4'
    entrypoint: [ "java", "-jar", "app.jar","bank1","1234","bank2","1235","bank3","1236","bank6","1239","borse4" ]
  borse5:
    build:
      context: .
      dockerfile: src/main/java/borse/Dockerfile
    container_name: 'borse5'
    entrypoint: [ "java", "-jar", "app.jar","bank1","1234","bank2","1235","bank3","1236","borse5" ]


  bank1:
    build:
      context: .
      dockerfile: src/main/java/bank/Dockerfile
    container_name: 'bank1'
    expose:
      - "8080"
    ports:
      - "8080:8080"
    entrypoint: ["java", "-jar", "app.jar", "bank1","1234","8080"]
  bank2:
    build:
      context: .
      dockerfile: src/main/java/bank/Dockerfile
    container_name: 'bank2'
    expose:
      - "8081"
    ports:
      - "8081:8081"
    entrypoint: [ "java", "-jar", "app.jar","bank2","1235","8081"]
  bank3:
    build:
      context: .
      dockerfile: src/main/java/bank/Dockerfile
    container_name: 'bank3'
    expose:
      - "8082"
    ports:
      - "8082:8082"
    entrypoint: [ "java", "-jar", "app.jar","bank3","1236","8082"]
  bank4:
    build:
      context: .
      dockerfile: src/main/java/bank/Dockerfile
    container_name: 'bank4'
    expose:
      - "8083"
    ports:
      - "8083:8083"
    entrypoint: [ "java", "-jar", "app.jar","bank4","1237","8083" ]
  bank5:
    build:
      context: .
      dockerfile: src/main/java/bank/Dockerfile
    container_name: 'bank5'
    expose:
      - "8084"
    ports:
      - "8084:8084"
    entrypoint: [ "java", "-jar", "app.jar","bank5","1238","8084" ]
  bank6:
    build:
      context: .
      dockerfile: src/main/java/bank/Dockerfile
    container_name: 'bank6'
    expose:
      - "8085"
    ports:
      - "8085:8085"
    entrypoint: [ "java", "-jar", "app.jar","bank3","1239","8085" ]

